### ISSUE TITLE
Missed tag 1.0.0

### ISSUE THREAD

**Issue by vkatsuba** [ipinfo/erlang#8]
Based on `hex.pm` current lib has version/tag `1.0.0` at the same time this tag is missed in GitHub.

**Comment by UmanShahzad** [comment]
Sorry about that; pushed the tag to the right commit: https://github.com/ipinfo/erlang/releases/tag/1.0.0

**Comment by UmanShahzad** [comment]
Will also push out a 1.0.1 for the latest work.

**Comment by vkatsuba** [comment]
@UmanShahzad if you want I can create CI script for auto publish lib into `hex.pm`.

**Comment by UmanShahzad** [comment]
@vkatsuba Nah it's all good: we don't necessarily want to always publish stuff on all `master` commits, it will depend on various things so doing it manually is better.

Thank you, though.

**Comment by vkatsuba** [comment]
I mean - auto publish to `hex.pm` when tag is provided in GitHub only.

**Comment by vkatsuba** [comment]
But... in any case, when you will need it - just ping me.

**Comment by UmanShahzad** [comment]
I definitely don't want to ask you for a bunch of free work @vkatsuba, so I'm hesitant. But personally, it's fine for me as it is and doesn't cost much to run `rebar3 hex publish` 😄

**Comment by vkatsuba** [comment]
Well.. not only `rebar3 hex publish`
1 - Create tag
2 - Authorise in `hex.pm`
3 - Change `*.app.src`
4 - Publish package

I propose just use step 1 and skip others. Plus this PR will take maybe.. 5 min of my time :upside_down_face:
BUT in any case, up to you.

**Comment by UmanShahzad** [comment]
True, it will require changing *.app.src too, but then that means it will have to also make a commit, which means I'll have to `git pull` that. So in the end it actually forces me to do multiple commands anyway 😄

**Comment by vkatsuba** [comment]
> True, it will require changing *.app.src too, but then that means it will have to also make a commit, which means I'll have to `git pull` that. So in the end it actually forces me to do multiple commands anyway smile

Nop :-). Only publish tag to GitHub will be needed from your end.
